config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'groups#index'
  resources :users,only: [ :edit, :update, :index] do
  end
  resources :groups,only: [ :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  namespace :api do
    resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :members
  has_many :messages
  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :members
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index 
    respond_to do |format|
      format.html
      format.json{ @messages = Message.where("id > ? && group_id = ?",params[:id],params[:group_id]) }
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [ :edit, :update]

  def index
  end
  
  def new
    @group  = Group.new
  end
  
  def create
      @group = Group.new(group_params)
      @group.users << current_user
    if @group.save
      redirect_to root_path, notice:'グループを作成しました'
    else
      render :new
    end
  end

    def update
      if @group.update(group_params)
        redirect_to group_messages_path(@group), notice: 'グループを編集しました'
      else
        render :edit
      end
    end
  
   def edit
   end
  

    private

    def group_params
      params.require(:group).permit(:name, {:user_ids => []})
    end

    def set_group
      @group = Group.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

 def index
  @message = Message.new
  @messages = @group.messages.includes(:user)
 end

 def create
    @message = @group.messages.new(message_params)
    @messages = @group.messages.includes(:user)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group),notice: 'メッセージが送信されました'}
        format.json
      end
    else
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
      end
    end
  
  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_chat-group-user.html.haml
#chat-group-users.chat-group-user.clearfix.js-chat-member
  = current_user.name
- @group.users.each do |user|
  #chat-group-users.chat-group-user.clearfix.js-chat-member
    %input{ name: "group[user_ids][]", type: "hidden", value: "#{user.id}" }
    - unless user.name == current_user.name
      %p.chat-group-user__name
        = user.name
        .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

app/views/groups/_chat-side.html.haml
.chat-side
  .chat-side__side--contents
    .chat-side__user
      .chat-side__name
        = current_user.name
      .chat-side__actions
        .chat-side_action
          = link_to edit_user_path(current_user) do
            %i.fa.fa-cog.fa-lg
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o.fa-lg

  .chat-side__groups
    .chat-side__group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          %p.chat-side__group-name
            = group.name
          %p.chat-side__group-message
            = group.show_last_message

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label user_search_field', placeholder: 'チャットメンバーを追加'
    .chat-group-form__field--right
      = f.text_field :members, id: "user-search-field", class: "chat-group-form__input", placeholder: "追加したいユーザ名を入力してください",value:""
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label user_search_field', placeholder: 'チャットメンバーを追加'
    .chat-group-form__field--right
      #chat-group-users
        = render 'chat-group-user', { group: @group }
  .chat-group-form__field.clearfix
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form',locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  .contents
    = render 'chat-side'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: {equiv: "Content-Type"}}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'messages/notifications'
    = yield

app/views/messages/_message.html.haml
.chat{data: {message_id: "#{message.id}"}}
%p.chat-main__body--name
  = message.user.name
%p.chat-main__body--time
  = message.created_at.strftime("%Y/%m/%d %H:%M")
.chat-main__body--messages
  - if message.body.present?
    = message.body
  = image_tag "#{message.image.url}", class: 'lower-message__image' if message.image.present? 

app/views/messages/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/messages/index.html.haml
= render 'groups/chat-side'
.chat-main{data: {group_id: "#{@group.id}"}}
  .chat-main__header
    .chat-main__header--left
      .chat-main__header--group-name
        = @group.name
    .chat-main__header--right
      = link_to "Edit", edit_group_path(@group), class: 'btn'
    %p.chat-main__header--members
      Members:
      %i
        - @group.users.each do |user|
          = user.name
  .chat-main__body
    = render @messages
  .chat-main__footer
    = form_for [@group,@message],:html => {:class => 'footer__form'} do |f|
      = f.text_field :body,class:"message", placeholder: "type a message"
      = f.label :image,class:"label" do
        = fa_icon 'picture-o'
      = f.file_field :image, class:'image'
      = f.submit "submit" ,class:"submit"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'